name: bob
version: 1.0.0.3

dependencies:
  - base

library:
  exposed-modules: Bob
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - bob
      - hspec
